function pick(source, keys) {
  const src = source && typeof source === "object" ? source : {};
  return keys.reduce((acc, key) => {
    if (Object.prototype.hasOwnProperty.call(src, key)) {
      acc[key] = src[key];
    }
    return acc;
  }, {});
}

const TOPBAR_KEYS = [
  "tab",
  "diagramActionBarRef",
  "bpmnRef",
  "isBpmnTab",
  "toText",
  "asObject",
  "diagramFocusMode",
  "setDiagramFocusMode",
  "diagramFullscreenActive",
  "toggleDiagramFullscreen",
  "setDiagramActionPathOpen",
  "setDiagramActionHybridToolsOpen",
  "setDiagramActionPlanOpen",
  "setDiagramActionPlaybackOpen",
  "setDiagramActionLayersOpen",
  "setDiagramActionRobotMetaOpen",
  "setRobotMetaListOpen",
  "setDiagramActionQualityOpen",
  "setDiagramActionOverflowOpen",
  "diagramActionLayersOpen",
  "diagramActionHybridToolsOpen",
  "hybridVisible",
  "drawioUiState",
  "overlayPanelModel",
  "hasSession",
  "activeQualityOverlayCount",
  "diagramActionQualityOpen",
  "diagramActionOverflowOpen",
];

const DRAWIO_LAYERS_KEYS = [
  "diagramActionLayersOpen",
  "diagramActionHybridToolsOpen",
  "diagramLayersPopoverRef",
  "markPlaybackOverlayInteraction",
  "hybridVisible",
  "hybridTotalCount",
  "showHybridLayer",
  "hideHybridLayer",
  "focusHybridLayer",
  "hybridModeEffective",
  "setHybridLayerMode",
  "hybridUiPrefs",
  "selectHybridPaletteTool",
  "setHybridLayerOpacity",
  "toggleHybridLayerLock",
  "toggleHybridLayerFocus",
  "drawioUiState",
  "openEmbeddedDrawioEditor",
  "toggleDrawioEnabled",
  "setDrawioOpacity",
  "toggleDrawioLock",
  "setDrawioElementVisible",
  "setDrawioElementLocked",
  "drawioFileInputRef",
  "exportEmbeddedDrawio",
  "hybridV2DocLive",
  "hybridV2HiddenCount",
  "revealAllHybridV2",
  "toggleHybridV2LayerVisibility",
  "toggleHybridV2LayerLock",
  "setHybridV2LayerOpacity",
  "hybridV2ActiveId",
  "hybridV2SelectedIds",
  "hybridLayerActiveElementId",
  "hybridV2BindPickMode",
  "setHybridV2BindPickMode",
  "goToActiveHybridBinding",
  "hybridV2BindingByHybridId",
  "exportHybridV2Drawio",
  "hybridV2FileInputRef",
  "hybridV2ImportNotice",
  "hybridLayerCounts",
  "hybridLayerVisibilityStats",
  "cleanupMissingHybridBindings",
  "hybridLayerRenderRows",
  "hybridV2Renderable",
  "setHybridV2ActiveId",
  "drawioSelectedElementId",
  "overlayPanelModel",
  "deleteOverlayEntity",
  "goToHybridLayerItem",
  "hideSelectedHybridItems",
  "lockSelectedHybridItems",
  "bpmnRef",
  "setDiagramActionLayersOpen",
  "setDiagramActionHybridToolsOpen",
];

const PLAYBACK_AUTOPASS_KEYS = [
  "diagramActionPlanOpen",
  "setDiagramActionPlanOpen",
  "diagramPlanPopoverRef",
  "executionPlanSource",
  "canExportExecutionPlan",
  "executionPlanBusy",
  "executionPlanPreview",
  "asObject",
  "asArray",
  "toText",
  "executionPlanError",
  "copyExecutionPlanFromDiagram",
  "downloadExecutionPlanFromDiagram",
  "saveExecutionPlanVersionFromDiagram",
  "executionPlanSaveBusy",
  "executionPlanVersions",
  "shortHash",
  "diagramActionPlaybackOpen",
  "setDiagramActionPlaybackOpen",
  "diagramPlaybackPopoverRef",
  "playbackGraphError",
  "playbackCanRun",
  "playbackScenarioLabel",
  "playbackScenarioKey",
  "setPlaybackScenarioKey",
  "playbackScenarioOptions",
  "playbackIndexClamped",
  "playbackTotal",
  "playbackCurrentEvent",
  "playbackEventTitle",
  "playbackGateways",
  "playbackGatewayChoices",
  "playbackGatewayPending",
  "playbackAwaitingGatewayId",
  "formatPlaybackGatewayTitle",
  "playbackGatewayOptionLabel",
  "setPlaybackGatewayChoice",
  "handlePlaybackGatewayDecision",
  "handlePlaybackPrev",
  "handlePlaybackTogglePlay",
  "handlePlaybackNext",
  "handlePlaybackReset",
  "playbackIsPlaying",
  "playbackSpeed",
  "setPlaybackSpeed",
  "playbackManualAtGateway",
  "setPlaybackManualAtGateway",
  "playbackAutoCamera",
  "setPlaybackAutoCamera",
  "autoPassUi",
  "autoPassError",
  "autoPassBlockedReason",
  "startAutoPass",
  "hasSession",
  "markPlaybackOverlayInteraction",
];

const PATHS_QUALITY_KEYS = [
  "diagramActionPathOpen",
  "setDiagramActionPathOpen",
  "diagramPathPopoverRef",
  "hasPathHighlightData",
  "pathHighlightEnabled",
  "setPathHighlightEnabled",
  "availablePathTiers",
  "pathHighlightCatalog",
  "pathHighlightTier",
  "setPathHighlightTier",
  "setPathHighlightSequenceKey",
  "availableSequenceKeysForTier",
  "pathHighlightSequenceKey",
  "openPathsFromDiagram",
  "openReportsFromDiagram",
  "toText",
  "asObject",
  "diagramActionQualityOpen",
  "setDiagramActionQualityOpen",
  "diagramQualityPopoverRef",
  "setQualityOverlayAll",
  "qualityOverlayRows",
  "qualityOverlayFilters",
  "toggleQualityOverlayFilter",
  "setQualityOverlayListKey",
  "setQualityOverlaySearch",
  "qualityOverlayListKey",
  "qualityOverlaySearch",
  "qualityOverlayListItems",
  "focusQualityOverlayItem",
  "diagramActionRobotMetaOpen",
  "setDiagramActionRobotMetaOpen",
  "diagramRobotMetaPopoverRef",
  "setRobotMetaListOpen",
  "robotMetaOverlayFilters",
  "toggleRobotMetaOverlayFilter",
  "showRobotMetaOverlay",
  "resetRobotMetaOverlay",
  "robotMetaCounts",
  "robotMetaListOpen",
  "diagramRobotMetaListRef",
  "robotMetaListSearch",
  "setRobotMetaListSearch",
  "robotMetaListTab",
  "setRobotMetaListTab",
  "robotMetaListItems",
  "focusRobotMetaItem",
];

const REPORTS_TEMPLATES_PROBLEMS_KEYS = [
  "templatesMenuOpen",
  "setTemplatesMenuOpen",
  "openTemplatesPicker",
  "canOpenTemplatesList",
  "templatesScope",
  "setTemplatesScope",
  "templatesActiveFolderId",
  "setTemplatesActiveFolder",
  "templatesFoldersByScope",
  "scopedTemplates",
  "reloadTemplatesAndFolders",
  "templatesBusy",
  "applyTemplate",
  "removeTemplate",
  "createTemplateFolderFromUi",
  "workspaceActiveOrgId",
  "canCreateOrgFolders",
  "openReportsFromDiagram",
  "openCreateTemplateModal",
  "canCreateTemplateFromSelection",
  "templateSelectionCount",
  "openSelectedElementNotes",
  "openSelectedElementAi",
  "canUseElementContextActions",
  "selectedInsertBetween",
  "openInsertBetweenModal",
  "insertBetweenBusy",
  "canInsertBetween",
  "insertBetweenErrorMessage",
];

const OVERFLOW_MODES_KEYS = [
  "diagramActionOverflowOpen",
  "setDiagramActionOverflowOpen",
  "diagramOverflowPopoverRef",
  "closeDiagramPopovers",
  "setDiagramActionPathOpen",
  "setDiagramActionPlaybackOpen",
  "setDiagramActionPlanOpen",
  "setDiagramActionRobotMetaOpen",
  "robotMetaOverlayEnabled",
  "setRobotMetaOverlayEnabled",
  "setRobotMetaOverlayFilters",
  "openCreateTemplateModal",
  "canCreateTemplateFromSelection",
  "templateSelectionCount",
  "openSelectedElementNotes",
  "openSelectedElementAi",
  "canUseElementContextActions",
  "selectedInsertBetween",
  "openInsertBetweenModal",
  "insertBetweenBusy",
  "canInsertBetween",
  "insertBetweenErrorMessage",
];

export function buildDiagramTopbarSectionView(view = {}) {
  return pick(view, TOPBAR_KEYS);
}

export function buildDiagramDrawioSectionView(view = {}) {
  return pick(view, DRAWIO_LAYERS_KEYS);
}

export function buildDiagramPlaybackSectionView(view = {}) {
  return pick(view, PLAYBACK_AUTOPASS_KEYS);
}

export function buildDiagramPathsQualitySectionView(view = {}) {
  return pick(view, PATHS_QUALITY_KEYS);
}

export function buildDiagramSecondaryActionsSectionView(view = {}) {
  return pick(view, REPORTS_TEMPLATES_PROBLEMS_KEYS);
}

export function buildDiagramOverflowSectionView(view = {}) {
  return pick(view, OVERFLOW_MODES_KEYS);
}

export default function buildDiagramControlsSections(view = {}) {
  return {
    topbar: buildDiagramTopbarSectionView(view),
    drawioLayers: buildDiagramDrawioSectionView(view),
    playbackAutopass: buildDiagramPlaybackSectionView(view),
    pathsQuality: buildDiagramPathsQualitySectionView(view),
    reportsTemplatesProblems: buildDiagramSecondaryActionsSectionView(view),
    overflowModes: buildDiagramOverflowSectionView(view),
  };
}
