export default function buildProcessDiagramOverlayLayersProps({
  activeProjectId,
  asObject,
  bpmnFragmentPlacementActive,
  bpmnFragmentPlacementGhost,
  bpmnRef,
  cleanupMissingHybridBindings,
  clientToDiagram,
  closeEmbeddedDrawioEditor,
  commitDrawioOverlayMove,
  createDrawioRuntimeElement,
  deleteDrawioOverlayElement,
  deleteSelectedHybridIds,
  diagramMode,
  draft,
  drawioEditorOpen,
  drawioModeEffective,
  drawioRuntimeToolState,
  drawioUiState,
  drawioVisible,
  getHybridLayerCardRefCallback,
  getOverlayViewportMatrix,
  handleAiQuestionsByElementChange,
  handleBpmnSelectionChange,
  handleDrawioEditorSave,
  handleHybridLayerItemPointerDown,
  handleHybridV2ElementContextMenu,
  handleHybridV2ElementDoubleClick,
  handleHybridV2ElementPointerDown,
  handleHybridV2OverlayContextMenu,
  handleHybridV2OverlayPointerDown,
  handleHybridV2ResizeHandlePointerDown,
  hybridDebugEnabled,
  hybridLayerActiveElementId,
  hybridLayerOverlayRef,
  hybridLayerRenderRows,
  hybridModeEffective,
  hybridOpacityValue,
  hybridPersist,
  hybridPlacementHitLayerActive,
  hybridSelection,
  hybridTools,
  hybridUiPrefs,
  hybridV2ActiveId,
  hybridV2BindingByHybridId,
  hybridV2DocLive,
  hybridV2PlaybackHighlightedIds,
  hybridV2Renderable,
  hybridV2SelectedIds,
  hybridV2SelectedIdSet,
  hybridVisible,
  isInterviewMode,
  onBpmnSaveLifecycleEvent,
  onElementNotesRemap,
  onSessionSync,
  propertiesOverlayAlwaysEnabled,
  propertiesOverlayAlwaysPreviewByElementId,
  queueDiagramMutation,
  reloadKey,
  robotMetaOverlayEnabled,
  robotMetaOverlayFilters,
  robotMetaStatusByElementId,
  selectedPropertiesOverlayPreview,
  setDrawioElementSize,
  setDrawioElementText,
  setDrawioElementTextWidth,
  setDrawioSelectedElementId,
  setHybridLayerActiveElementId,
  sid,
  stepTimeUnit,
  subscribeOverlayViewportMatrix,
  tab,
  toText,
  withHybridOverlayGuard,
  hybridViewportMatrix,
  hybridViewportMatrixRef,
}) {
  return {
    bpmnStageProps: {
      ref: bpmnRef,
      sessionId: sid,
      activeProjectId,
      view: tab === "xml" ? "xml" : "editor",
      draft,
      reloadKey,
      onDiagramMutation: queueDiagramMutation,
      onElementSelectionChange: handleBpmnSelectionChange,
      onElementNotesRemap: onElementNotesRemap,
      onAiQuestionsByElementChange: handleAiQuestionsByElementChange,
      onSessionSync,
      onSaveLifecycleEvent: onBpmnSaveLifecycleEvent,
      aiQuestionsModeEnabled: isInterviewMode,
      diagramDisplayMode: diagramMode,
      stepTimeUnit,
      robotMetaOverlayEnabled,
      robotMetaOverlayFilters,
      robotMetaStatusByElementId,
      selectedPropertiesOverlayPreview,
      propertiesOverlayAlwaysEnabled,
      propertiesOverlayAlwaysPreviewByElementId,
    },
    fragmentGhostProps: {
      active: bpmnFragmentPlacementActive,
      ghost: bpmnFragmentPlacementGhost,
    },
    drawioOverlayProps: {
      visible: tab === "diagram" && drawioVisible,
      drawioMeta: drawioUiState,
      drawioMode: drawioModeEffective,
      drawioActiveTool: drawioRuntimeToolState,
      overlayMatrix: hybridViewportMatrix,
      overlayMatrixRef: hybridViewportMatrixRef,
      subscribeOverlayMatrix: subscribeOverlayViewportMatrix,
      getOverlayMatrix: getOverlayViewportMatrix,
      screenToDiagram: clientToDiagram,
      onCommitMove: commitDrawioOverlayMove,
      onCommitResize: setDrawioElementSize,
      onCommitTextResize: setDrawioElementTextWidth,
      onCommitText: setDrawioElementText,
      onCreateElement: createDrawioRuntimeElement,
      onDeleteElement: deleteDrawioOverlayElement,
      onSelectionChange: setDrawioSelectedElementId,
    },
    hybridOverlayProps: {
      visible: tab === "diagram" && hybridVisible,
      modeEffective: hybridModeEffective,
      uiPrefs: hybridUiPrefs,
      opacityValue: hybridOpacityValue,
      overlayRef: hybridLayerOverlayRef,
      placementHitLayerActive: hybridPlacementHitLayerActive,
      onOverlayPointerDown: handleHybridV2OverlayPointerDown,
      onOverlayPointerMove: hybridTools.onOverlayPointerMove,
      onOverlayPointerLeave: hybridTools.onOverlayPointerLeave,
      onOverlayContextMenu: handleHybridV2OverlayContextMenu,
      v2Renderable: hybridV2Renderable,
      v2ActiveId: hybridV2ActiveId,
      v2SelectedIds: hybridV2SelectedIdSet,
      v2PlaybackHighlightedIds: hybridV2PlaybackHighlightedIds,
      v2BindingByHybridId: hybridV2BindingByHybridId,
      onV2ElementPointerDown: handleHybridV2ElementPointerDown,
      onV2ElementContextMenu: handleHybridV2ElementContextMenu,
      onV2ElementDoubleClick: handleHybridV2ElementDoubleClick,
      onV2ResizeHandlePointerDown: handleHybridV2ResizeHandlePointerDown,
      v2GhostPreview: hybridTools.ghostPreview,
      v2ArrowPreview: hybridTools.arrowPreview,
      v2TextEditor: hybridTools.textEditor,
      onV2TextEditorChange: hybridTools.updateTextEditorValue,
      onV2TextEditorCommit: hybridTools.commitTextEditor,
      onV2TextEditorCancel: hybridTools.closeTextEditor,
      legacyRows: hybridLayerRenderRows,
      legacyActiveElementId: hybridLayerActiveElementId,
      debugEnabled: hybridDebugEnabled,
      onLegacyHotspotMouseDown: (event, elementId) => {
        withHybridOverlayGuard(event, { action: "hotspot_mousedown", elementId });
      },
      onLegacyHotspotClick: (event, elementId) => {
        withHybridOverlayGuard(event, { action: "hotspot_click", elementId });
        setHybridLayerActiveElementId(elementId);
        bpmnRef.current?.focusNode?.(elementId, { keepPrevious: false, durationMs: 1200 });
      },
      onLegacyCardMouseDown: handleHybridLayerItemPointerDown,
      onLegacyCardClick: (event, elementId) => {
        withHybridOverlayGuard(event, { action: "card_click", elementId });
      },
      onLegacyMissingCleanupMouseDown: (event, elementId) => {
        withHybridOverlayGuard(event, { action: "card_missing_cleanup_mousedown", elementId });
      },
      onLegacyMissingCleanupClick: (event, elementId) => {
        withHybridOverlayGuard(event, { action: "card_missing_cleanup_click", elementId });
        cleanupMissingHybridBindings("card_missing_cleanup");
      },
      onLegacyCardRef: getHybridLayerCardRefCallback,
    },
    hybridContextMenuProps: {
      menu: hybridTools.contextMenu,
      selectionCount: hybridSelection.selectionCount,
      canRename: hybridSelection.selectionCount === 1
        && !!hybridV2DocLive.elements.find((row) => toText(asObject(row).id) === hybridV2ActiveId),
      onClose: hybridTools.closeContextMenu,
      onDelete: () => {
        deleteSelectedHybridIds();
        hybridTools.closeContextMenu();
      },
      onRename: () => {
        hybridTools.renameHybridItem(hybridV2ActiveId);
        hybridTools.closeContextMenu();
      },
      onHide: () => {
        hybridTools.hideHybridIds(hybridV2SelectedIds);
        hybridTools.closeContextMenu();
      },
      onLock: () => {
        hybridTools.lockLayersForHybridIds(hybridV2SelectedIds);
        hybridTools.closeContextMenu();
      },
    },
    hybridPersistToastProps: {
      visible: tab === "diagram" && !!hybridPersist.lockBusyNotice?.open,
      message: hybridPersist.lockBusyNotice?.message,
      pendingDraft: !!hybridPersist.pendingDraft,
      onRetry: () => {
        void hybridPersist.retryLast();
      },
      onDismiss: hybridPersist.dismissLockBusyNotice,
    },
    drawioEditorModalProps: {
      open: drawioEditorOpen,
      title: "Draw.io Editor",
      initialXml: drawioUiState.doc_xml,
      onSave: handleDrawioEditorSave,
      onClose: closeEmbeddedDrawioEditor,
    },
  };
}
