import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";

const topBarSource = fs.readFileSync(new URL("./TopBar.jsx", import.meta.url), "utf8");
const appShellSource = fs.readFileSync(new URL("./AppShell.jsx", import.meta.url), "utf8");
const appSource = fs.readFileSync(new URL("../App.jsx", import.meta.url), "utf8");

test("TopBar exposes bounded discussion notification entry from existing note aggregate truth", () => {
  assert.match(topBarSource, /useSessionNoteAggregate\(effectiveSessionId\)/);
  assert.match(topBarSource, /useSessionNoteAggregates\(sessionAggregateIds\)/);
  assert.match(topBarSource, /buildAccountDiscussionNotificationGroups/);
  assert.match(topBarSource, /noteNotificationsAvailable/);
  assert.match(topBarSource, /hasBackendNotificationFeed \? noteNotificationItems : \[\]/);
  assert.match(topBarSource, /hasBackendNotificationFeed \? \[\] : mentionItems/);
  assert.match(topBarSource, /hasBackendNotificationFeed \? new Map\(\) : aggregates/);
  assert.match(topBarSource, /item\.reason === "mention" && item\.mention/);
  assert.doesNotMatch(topBarSource, /apiGetSessionNoteAggregate/);
  assert.doesNotMatch(topBarSource, /data-testid="topbar-mentions-button"/);
  assert.match(topBarSource, /data-testid="topbar-account-button"/);
  assert.match(topBarSource, /data-testid="topbar-account-notification-count"/);
  assert.match(topBarSource, /data-testid="topbar-mentions-menu"/);
  assert.match(topBarSource, /data-testid="topbar-notification-center"/);
  assert.match(topBarSource, /data-testid="topbar-notification-session-group"/);
  assert.match(topBarSource, /data-testid="topbar-notification-empty"/);
  assert.match(topBarSource, /"topbar-discussion-notifications"/);
  assert.match(topBarSource, /data-notes-panel-trigger=\{isCurrentAggregate \? "true" : undefined\}/);
  assert.match(topBarSource, /onOpenDiscussionNotifications\?\.\(\{/);
  assert.match(topBarSource, /accountNotificationCount = accountNotificationCenter\.badgeCount/);
  assert.match(topBarSource, /hasAccountNotifications = accountNotificationCenter\.rowCount > 0/);
  assert.match(topBarSource, /Нет активных уведомлений/);
  assert.match(topBarSource, /Новые сообщения и упоминания из обсуждений появятся здесь\./);
  assert.doesNotMatch(topBarSource, /personalDiscussionCount/);
  assert.match(topBarSource, /fixed right-3 top-14/);
  assert.match(topBarSource, /max-h-\[calc\(100vh-4\.25rem\)\]/);
  assert.match(topBarSource, /flex max-h-\[calc\(100vh-4\.25rem\)\][\s\S]*overflow-hidden rounded-xl[\s\S]*data-testid="topbar-account-menu"/);
  assert.match(topBarSource, /flex min-h-0 flex-1 flex-col border-b[\s\S]*data-testid="topbar-mentions-menu"/);
  assert.match(topBarSource, /"topbar-mention-item"/);
  assert.match(topBarSource, /w-\[480px\]/);
  assert.match(topBarSource, /max-w-\[calc\(100vw-1\.5rem\)\]/);
  assert.match(topBarSource, /flex max-h-\[calc\(100vh-4\.25rem\)\]/);
  assert.match(topBarSource, /data-testid="topbar-account-actions"/);
  assert.match(topBarSource, /min-h-0 flex-1 overflow-y-auto[\s\S]*data-testid="topbar-notification-center"/);
  assert.match(topBarSource, /group w-full min-w-0 overflow-hidden rounded-md px-2 py-2/);
  assert.match(topBarSource, />\s*Открыть\s*</);
  assert.match(topBarSource, /line-clamp-2 break-words/);
  assert.match(topBarSource, /row\.badges\?\.slice\(0, 4\)/);
  assert.match(topBarSource, /shortLabel\(group\.sessionTitle, 46\)/);
  assert.match(topBarSource, /shortLabel\(group\.projectTitle, 54\)/);
  assert.doesNotMatch(topBarSource, /w-\[min\(340px,calc\(100vw-1\.5rem\)\)\]/);
  assert.doesNotMatch(topBarSource, /max-h-\[286px\]/);
  assert.doesNotMatch(topBarSource, /rounded-lg border border-border\/70 bg-panel2\/45/);
  assert.doesNotMatch(topBarSource, /rounded-md border border-border\/70 bg-bg\/35/);
  assert.doesNotMatch(topBarSource, /Здесь появятся персональные упоминания из обсуждений\./);
  assert.match(topBarSource, /overflow-y-auto/);
  assert.match(topBarSource, /groups\.slice\(0, 8\)/);
  assert.match(topBarSource, /rows\.slice\(0, 3\)/);
});

test("TopBar profile menu uses a direct theme switch instead of settings row", () => {
  assert.match(topBarSource, /data-testid="topbar-theme-toggle"/);
  assert.match(topBarSource, /role="switch"/);
  assert.match(topBarSource, /aria-checked=\{uiTheme === "light" \? "true" : "false"\}/);
  assert.match(topBarSource, /toggleTheme\(\)/);
  assert.match(topBarSource, /secondaryBtn h-9 w-full min-w-0 justify-start gap-2 overflow-hidden[\s\S]*data-testid="topbar-theme-toggle"/);
  assert.match(topBarSource, /relative h-5 w-9 shrink-0/);
  assert.match(topBarSource, /Тёмная/);
  assert.match(topBarSource, /Светлая/);
  assert.doesNotMatch(topBarSource, /data-testid="topbar-account-settings"/);
  assert.doesNotMatch(topBarSource, />Настройки</);
});

test("App bridge opens NotesMvpPanel in notification mode without a new router", () => {
  assert.match(appShellSource, /onOpenDiscussionNotifications/);
  assert.match(appShellSource, /<TopBar[\s\S]*onOpenDiscussionNotifications=\{onOpenDiscussionNotifications\}/);
  assert.match(appShellSource, /noteNotifications=\{noteNotifications\}/);
  assert.match(appShellSource, /noteNotificationsAvailable=\{noteNotificationsAvailable\}/);
  assert.match(appSource, /apiListNoteNotifications/);
  assert.match(appSource, /Promise\.allSettled\(\[/);
  assert.match(appSource, /apiListNoteNotifications\(\{ limit: 20, includeRead: false \}\)/);
  assert.match(appSource, /setNoteNotificationsAvailable\(true\)/);
  assert.match(appSource, /setNoteNotificationsAvailable\(false\)/);
  assert.match(appSource, /const mode = String\(options\?\.mode \|\| "discussions"\)\.trim\(\) === "notifications" \? "notifications" : "discussions";/);
  assert.match(appSource, /mode: "notifications"/);
  assert.match(appSource, /source: "topbar_discussion_notifications"/);
  assert.match(appSource, /threadId: options\?\.threadId \|\| options\?\.thread_id \|\| ""/);
  assert.match(appSource, /commentId: options\?\.commentId \|\| options\?\.comment_id \|\| ""/);
  assert.match(appSource, /onFocusNotificationTarget=\{focusDiscussionNotificationTarget\}/);
  assert.match(appSource, /currentUserId=\{user\?\.id\}/);
});
