export const ADMIN_STATUS_META = {
  ok: { tone: "ok", label: "OK" },
  on: { tone: "ok", label: "ON" },
  ready: { tone: "ok", label: "Ready" },
  done: { tone: "ok", label: "Done" },
  completed: { tone: "ok", label: "Completed" },
  normal: { tone: "ok", label: "Normal" },
  running: { tone: "accent", label: "Running" },
  queued: { tone: "accent", label: "Queued" },
  pending: { tone: "accent", label: "Pending" },
  degraded: { tone: "warn", label: "Degraded" },
  incident: { tone: "danger", label: "Incident" },
  draft: { tone: "default", label: "Draft" },
  in_progress: { tone: "warn", label: "In Progress" },
  missing: { tone: "warn", label: "Missing" },
  fallback: { tone: "warn", label: "Fallback" },
  off: { tone: "warn", label: "Off" },
  misconfigured: { tone: "danger", label: "Misconfigured" },
  failed: { tone: "danger", label: "Failed" },
  fail: { tone: "danger", label: "Fail" },
  error: { tone: "danger", label: "Error" },
  idle: { tone: "default", label: "Idle" },
  unknown: { tone: "default", label: "Unknown" },
};
