export const ADMIN_STATUS_META = {
  ok: { tone: "ok", label: "OK" },
  on: { tone: "ok", label: "ON" },
  active: { tone: "accent", label: "Активен" },
  healthy: { tone: "ok", label: "Здорово" },
  empty: { tone: "default", label: "Пусто" },
  scoped: { tone: "default", label: "В контуре" },
  ready: { tone: "ok", label: "Готово" },
  done: { tone: "ok", label: "Готово" },
  completed: { tone: "ok", label: "Завершено" },
  normal: { tone: "ok", label: "Норма" },
  running: { tone: "accent", label: "Выполняется" },
  queued: { tone: "accent", label: "В очереди" },
  pending: { tone: "accent", label: "Ожидает" },
  degraded: { tone: "warn", label: "Деградация" },
  incident: { tone: "danger", label: "Инцидент" },
  draft: { tone: "default", label: "Черновик" },
  in_progress: { tone: "warn", label: "В работе" },
  missing: { tone: "warn", label: "Отсутствует" },
  fallback: { tone: "warn", label: "Fallback" },
  off: { tone: "warn", label: "Выключено" },
  misconfigured: { tone: "danger", label: "Неверная конфигурация" },
  failed: { tone: "danger", label: "Ошибка" },
  fail: { tone: "danger", label: "Ошибка" },
  error: { tone: "danger", label: "Ошибка" },
  idle: { tone: "default", label: "Простой" },
  unknown: { tone: "default", label: "Неизвестно" },
};
