function explainability({
  code,
  label,
  description,
  whatChecked,
  howCalculated,
  source,
  impact,
}) {
  return Object.freeze({
    code: String(code || "").trim(),
    label: String(label || "").trim(),
    description: String(description || "").trim(),
    whatChecked: String(whatChecked || "").trim(),
    howCalculated: String(howCalculated || "").trim(),
    source: String(source || "").trim(),
    impact: String(impact || "").trim(),
  });
}

export const DOD_EXPLAINABILITY = Object.freeze({
  summary: Object.freeze({
    readiness: explainability({
      code: "SUM_001",
      label: "Общая готовность",
      description: "Итоговый readiness-показатель по всем разделам.",
      whatChecked: "Общий уровень готовности PM по разделам.",
      howCalculated: "Взвешенная сумма секционных оценок.",
      source: "Агрегированный readiness snapshot (real).",
      impact: "Информационный итог; показывает текущее состояние готовности.",
    }),
    document: explainability({
      code: "SUM_002",
      label: "Документ",
      description: "Профиль готовности к документированию процесса.",
      whatChecked: "Полнота документной части процесса.",
      howCalculated: "Структурные и step-completeness сигналы document-профиля.",
      source: "readiness profile: document (real).",
      impact: "Влияет на документный профиль, не эквивалентен automation-ready.",
    }),
    automation: explainability({
      code: "SUM_003",
      label: "Автоматизация",
      description: "Профиль пригодности к автоматизации/исполнению.",
      whatChecked: "Готовность path/sequence/terminal semantics и execution checks.",
      howCalculated: "Агрегация path + sequence + AutoPass сигналов.",
      source: "BPMN, bpmn_meta, AutoPass слой (real).",
      impact: "Критичен для automation readiness.",
    }),
    audit: explainability({
      code: "SUM_004",
      label: "Аудит",
      description: "Профиль трассировки и проверяемости.",
      whatChecked: "Наличие audit/traceability покрытия.",
      howCalculated: "По trace chain, audit events и consistency.",
      source: "org/workspace/project/session audit layer (real).",
      impact: "Влияет на audit-профиль и прозрачность проверки.",
    }),
    blockers: explainability({
      code: "SUM_005",
      label: "Блокеры",
      description: "Счётчик проблем hard severity.",
      whatChecked: "Количество проблем, мешающих принять готовность.",
      howCalculated: "Count issues с hard severity.",
      source: "readiness issues (real).",
      impact: "Hard gate: блокируют итоговую готовность.",
    }),
    gaps: explainability({
      code: "SUM_006",
      label: "Пробелы",
      description: "Счётчик неблокирующих пробелов качества.",
      whatChecked: "Количество soft issues/warnings.",
      howCalculated: "Count проблем soft-класса.",
      source: "readiness issues (real).",
      impact: "Soft score: не блокируют, но снижают итоговый процент.",
    }),
  }),
  columns: Object.freeze({
    section: explainability({
      code: "COL_001",
      label: "Раздел",
      description: "Раздел readiness-проверок.",
      whatChecked: "Предметная зона контроля качества.",
      howCalculated: "Фиксированный каталог разделов DoD.",
      source: "readiness config (real).",
      impact: "Помогает локализовать проблемы по областям.",
    }),
    weight: explainability({
      code: "COL_002",
      label: "Вес",
      description: "Значимость раздела в формуле.",
      whatChecked: "Вес секции в итоговой оценке.",
      howCalculated: "Фиксированный коэффициент в конфиге readiness.",
      source: "readiness config (real).",
      impact: "Определяет размер вклада в итог.",
    }),
    sectionPercent: explainability({
      code: "COL_003",
      label: "% раздела",
      description: "Локальная оценка секции.",
      whatChecked: "Процент прохождения проверок секции.",
      howCalculated: "Из набора checks внутри раздела.",
      source: "section readiness data (real).",
      impact: "Участвует в итоговом score.",
    }),
    contribution: explainability({
      code: "COL_004",
      label: "Вклад в итог",
      description: "Вклад секции в итоговый readiness.",
      whatChecked: "Сколько процентов секция добавляет в общий итог.",
      howCalculated: "Вес × % раздела.",
      source: "derived score (real).",
      impact: "Прямо меняет общий показатель.",
    }),
    type: explainability({
      code: "COL_005",
      label: "Тип",
      description: "Класс сигнала: hard/soft/mixed.",
      whatChecked: "Блокирующая или скоринговая природа секции.",
      howCalculated: "Задаётся конфигурацией секции.",
      source: "readiness config (real).",
      impact: "Показывает, может ли секция блокировать готовность.",
    }),
    status: explainability({
      code: "COL_006",
      label: "Статус",
      description: "Текущее состояние секции.",
      whatChecked: "Уровень прохождения секционных проверок.",
      howCalculated: "Сопоставление процента секции с порогами.",
      source: "section readiness data (real).",
      impact: "Сигнал приоритета исправлений.",
    }),
  }),
  sections: Object.freeze({
    structure_graph: explainability({
      code: "SEC_001",
      label: "Структура / Граф",
      description: "Целостность BPMN-графа.",
      whatChecked: "Start/End, reachability, dead-end, gateway integrity.",
      howCalculated: "Парсинг BPMN графа и structural checks.",
      source: "bpmn_xml.",
      impact: "Жёсткий сигнал: может блокировать готовность.",
    }),
    paths_sequence: explainability({
      code: "SEC_002",
      label: "Пути / Последовательность",
      description: "Корректность path/tier/sequence логики.",
      whatChecked: "Path assignment, P0/P1/P2, sequence_key, XOR guards.",
      howCalculated: "Проверка path metadata и route contracts.",
      source: "bpmn_meta / readiness config.",
      impact: "Жёсткий сигнал для path-consistency.",
    }),
    autopass_execution: explainability({
      code: "SEC_003",
      label: "AutoPass / Исполнение",
      description: "Проходимость основного процесса.",
      whatChecked: "Достижение корректного EndEvent в precheck/run.",
      howCalculated: "AutoPass precheck + execution result.",
      source: "AutoPass engine / auto_pass_v1.",
      impact: "Жёсткий сигнал automation readiness.",
    }),
    steps_completeness: explainability({
      code: "SEC_004",
      label: "Полнота шагов",
      description: "Полнота описания шагов.",
      whatChecked: "Заполненность role/equipment/notes и coverage полей.",
      howCalculated: "Step-level completeness checks.",
      source: "timeline/interview/derived step data.",
      impact: "Мягкий сигнал; снижает score.",
    }),
    traceability_audit: explainability({
      code: "SEC_005",
      label: "Трассируемость / Аудит",
      description: "Прослеживаемость сущностей и событий.",
      whatChecked: "Trace chain, audit events, reference consistency.",
      howCalculated: "Агрегация trace и audit checks.",
      source: "org/workspace/project/session audit layer.",
      impact: "Смешанный сигнал: compliance + score.",
    }),
    readiness_artifacts: explainability({
      code: "SEC_006",
      label: "Артефакты готовности",
      description: "Наличие вспомогательных readiness signals.",
      whatChecked: "Полнота derived artifacts snapshot.",
      howCalculated: "Artifact completeness checks.",
      source: "workspace/session derived data.",
      impact: "Мягкий сигнал; не BPMN truth.",
    }),
  }),
  statuses: Object.freeze({
    ok: explainability({
      code: "STS_OK",
      label: "OK",
      description: "Секция проходит целевые критерии.",
      whatChecked: "Порог качества достигнут.",
      howCalculated: "Статус выставляется при достижении верхнего порога.",
      source: "section readiness state.",
      impact: "Не блокирует и минимально давит на score.",
    }),
    warning: explainability({
      code: "STS_WARN",
      label: "Warning",
      description: "В секции есть заметные отклонения.",
      whatChecked: "Часть проверок секции не проходит.",
      howCalculated: "Статус между OK и слабым состоянием.",
      source: "section readiness state.",
      impact: "Обычно soft-снижение, но требует внимания.",
    }),
    partial: explainability({
      code: "STS_PARTIAL",
      label: "Partial",
      description: "Секция заполнена частично.",
      whatChecked: "Недостаточное покрытие секционных checks.",
      howCalculated: "Частичное прохождение набора критериев.",
      source: "section readiness state.",
      impact: "Снижает score, может породить soft gaps.",
    }),
    weak: explainability({
      code: "STS_WEAK",
      label: "Weak",
      description: "Секция значительно проседает.",
      whatChecked: "Низкая доля пройденных проверок.",
      howCalculated: "Статус нижнего порога по секции.",
      source: "section readiness state.",
      impact: "Сильный негативный вклад в итоговый процент.",
    }),
  }),
  types: Object.freeze({
    hard: explainability({
      code: "TYPE_HARD",
      label: "Жёсткий",
      description: "Сигналы hard-класса.",
      whatChecked: "Критерии, влияющие на блокировку.",
      howCalculated: "Тип задан в readiness config.",
      source: "readiness config.",
      impact: "Может блокировать готовность (hard gate).",
    }),
    soft: explainability({
      code: "TYPE_SOFT",
      label: "Мягкий",
      description: "Сигналы score-класса.",
      whatChecked: "Критерии полноты без hard-block.",
      howCalculated: "Тип задан в readiness config.",
      source: "readiness config.",
      impact: "Не блокирует, влияет на score.",
    }),
    mixed: explainability({
      code: "TYPE_MIXED",
      label: "Смешанный",
      description: "Комбинация hard и soft сигналов.",
      whatChecked: "Часть критериев блокирует, часть скорирует.",
      howCalculated: "Тип задан в readiness config.",
      source: "readiness config.",
      impact: "Влияет и на gate, и на score.",
    }),
  }),
  groups: Object.freeze({
    blockers: explainability({
      code: "GRP_BLOCKERS",
      label: "Жёсткие блокеры",
      description: "Проблемы, мешающие принять PM как готовый.",
      whatChecked: "Hard severity issues.",
      howCalculated: "Фильтрация issues по hard severity.",
      source: "readiness issues.",
      impact: "Hard gate: блокируют готовность.",
    }),
    gaps: explainability({
      code: "GRP_GAPS",
      label: "Неблокирующие пробелы",
      description: "Недозаполненные места без блокировки.",
      whatChecked: "Soft issues и warning gaps.",
      howCalculated: "Фильтрация issues по soft severity.",
      source: "readiness issues.",
      impact: "Soft score: не блокируют, но снижают оценку.",
    }),
  }),
  impacts: Object.freeze({
    hardGate: explainability({
      code: "IMPACT_HARD",
      label: "hard gate",
      description: "Сигнал участвует в блокировке готовности.",
      whatChecked: "Критерии обязательного прохождения.",
      howCalculated: "Привязка правила к hard severity.",
      source: "readiness config + issues.",
      impact: "Блокирует итог до исправления.",
    }),
    softScore: explainability({
      code: "IMPACT_SOFT",
      label: "soft score",
      description: "Сигнал влияет на процент, но не блокирует.",
      whatChecked: "Критерии полноты и качества описания.",
      howCalculated: "Привязка правила к soft severity.",
      source: "readiness config + issues.",
      impact: "Снижает итоговый score.",
    }),
  }),
  issues: Object.freeze({
    STR_003: explainability({
      code: "STR_003",
      label: "Тупиковый узел без EndEvent",
      description: "В графе найден dead-end, не являющийся EndEvent.",
      whatChecked: "Корректность terminal semantics в BPMN.",
      howCalculated: "Dead-end check по направленным рёбрам графа.",
      source: "bpmn_xml.",
      impact: "Hard blocker.",
    }),
    PATH_002: explainability({
      code: "PATH_002",
      label: "Отсутствует sequence_key",
      description: "У path-узлов отсутствует sequence_key.",
      whatChecked: "Наличие sequence_key у узлов маршрутов.",
      howCalculated: "Проверка path node metadata по обязательному полю.",
      source: "bpmn_meta.",
      impact: "Hard blocker.",
    }),
    EXEC_001: explainability({
      code: "EXEC_001",
      label: "AutoPass не доходит до EndEvent",
      description: "AutoPass precheck не достигает главного конца процесса.",
      whatChecked: "Проходимость главного маршрута до EndEvent.",
      howCalculated: "Анализ результата AutoPass precheck.",
      source: "AutoPass engine.",
      impact: "Hard blocker.",
    }),
    STEP_001: explainability({
      code: "STEP_001",
      label: "Недостаток заметок / AI-покрытия",
      description: "Не хватает заметок или AI-покрытия у шагов.",
      whatChecked: "Наличие notes/AI coverage по шагам.",
      howCalculated: "Count шагов без нужного покрытия.",
      source: "timeline/interview/derived data.",
      impact: "Soft score.",
    }),
    STEP_002: explainability({
      code: "STEP_002",
      label: "Не указано оборудование",
      description: "У части шагов отсутствует оборудование.",
      whatChecked: "Заполненность equipment поля.",
      howCalculated: "Count шагов с пустым equipment.",
      source: "timeline/interview/derived data.",
      impact: "Soft score.",
    }),
    READY_001: explainability({
      code: "READY_001",
      label: "Неполны артефакты readiness",
      description: "Неполный snapshot артефактов readiness.",
      whatChecked: "Полнота вспомогательных readiness artifacts.",
      howCalculated: "Artifact completeness check.",
      source: "workspace/session derived data.",
      impact: "Soft score.",
    }),
  }),
  sources: Object.freeze({
    bpmn_xml: explainability({
      code: "SRC_BPMN_XML",
      label: "bpmn_xml",
      description: "Сигнал вычислен из BPMN XML.",
      whatChecked: "Графовые и структурные свойства процесса.",
      howCalculated: "Парсинг XML и обход графа.",
      source: "BPMN-модель сессии.",
      impact: "Часто участвует в hard сигнале.",
    }),
    bpmn_meta: explainability({
      code: "SRC_BPMN_META",
      label: "bpmn_meta",
      description: "Сигнал вычислен из metadata узлов/потоков.",
      whatChecked: "Path tags, sequence, tiers, annotations.",
      howCalculated: "Проверка contract-полей в metadata.",
      source: "session.bpmn_meta.",
      impact: "Влияет на path/sequence корректность.",
    }),
    autopass: explainability({
      code: "SRC_AUTOPASS",
      label: "AutoPass",
      description: "Сигнал из execution engine AutoPass.",
      whatChecked: "Проходимость процесса и достижение конца.",
      howCalculated: "Precheck/run status и diagnostics.",
      source: "auto_pass_v1.",
      impact: "Критично для automation readiness.",
    }),
    derived_step_data: explainability({
      code: "SRC_DERIVED_STEPS",
      label: "derived",
      description: "Сигнал из derived step data.",
      whatChecked: "Полнота описания шагов.",
      howCalculated: "Агрегация по timeline/interview полям.",
      source: "timeline/interview/derived data.",
      impact: "Обычно soft score.",
    }),
    derived_artifacts: explainability({
      code: "SRC_DERIVED_ART",
      label: "derived_artifacts",
      description: "Сигнал из derived readiness artifacts.",
      whatChecked: "Completeness вспомогательных артефактов.",
      howCalculated: "Artifact snapshot check.",
      source: "workspace/session derived data.",
      impact: "Soft score.",
    }),
  }),
  to100: Object.freeze({
    todo_1: explainability({
      code: "TODO_001",
      label: "Добавить sequence_key у 4 узлов",
      description: "Доработка path metadata для стабильной последовательности.",
      whatChecked: "Наличие sequence_key у узлов маршрута.",
      howCalculated: "После заполнения правила PATH_002 переходят в pass; uplift по весу секции.",
      source: "bpmn_meta + section weight (Пути / Последовательность).",
      impact: "Hard uplift: повышает readiness и снимает блокировку path-секции.",
    }),
    todo_2: explainability({
      code: "TODO_002",
      label: "Исправить 1 тупиковый path",
      description: "Убрать dead-end без EndEvent.",
      whatChecked: "Terminal корректность структуры графа.",
      howCalculated: "Fix STR_003 улучшает секцию структуры с её весом.",
      source: "bpmn_xml + section weight (Структура / Граф).",
      impact: "Hard uplift: убирает blocker по структуре.",
    }),
    todo_3: explainability({
      code: "TODO_003",
      label: "Заполнить role/equipment у 6 шагов",
      description: "Повышение completeness шагов.",
      whatChecked: "Заполненность role/equipment в step fields.",
      howCalculated: "Снижение soft gaps поднимает % секции полноты.",
      source: "timeline/interview/derived step data.",
      impact: "Soft uplift: увеличивает score без hard gate.",
    }),
    todo_4: explainability({
      code: "TODO_004",
      label: "Перезапустить AutoPass после фикса конца",
      description: "Подтверждение исполнимости процесса.",
      whatChecked: "Достижение корректного EndEvent в AutoPass.",
      howCalculated: "Обновление статуса AutoPass после фикса графа.",
      source: "AutoPass engine + structure fixes.",
      impact: "Hard uplift для automation-профиля.",
    }),
    todo_5: explainability({
      code: "TODO_005",
      label: "Добавить заметки / AI-детали для 8 шагов",
      description: "Повышение quality coverage шагов.",
      whatChecked: "Наличие notes/AI details на шагах.",
      howCalculated: "Снижение STEP_001 soft-gap повышает % секции.",
      source: "timeline/interview/derived step data.",
      impact: "Soft uplift: добавляет score без блокировки.",
    }),
  }),
});

function collectNodeEntries(node, out, path) {
  if (!node || typeof node !== "object") return;
  const currentPath = path ? `${path}` : "";
  const hasFields = ["code", "label", "description", "whatChecked", "howCalculated", "source", "impact"].every((key) => {
    return Object.prototype.hasOwnProperty.call(node, key);
  });
  if (hasFields) {
    out.push({ path: currentPath, value: node });
    return;
  }
  Object.keys(node).forEach((key) => {
    const nextPath = currentPath ? `${currentPath}.${key}` : key;
    collectNodeEntries(node[key], out, nextPath);
  });
}

export function listDodExplainabilityEntries() {
  const out = [];
  collectNodeEntries(DOD_EXPLAINABILITY, out, "");
  return out;
}
