#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RUNTIME_ENV_FILE="${ROOT_DIR}/.runtime_source.env"
BASE_COMPOSE_FILE="${ROOT_DIR}/docker-compose.yml"
SOURCE_COMPOSE_FILE="${ROOT_DIR}/docker-compose.source-root.yml"
BASE_ENV_FILE="${ROOT_DIR}/.env"

usage() {
  cat <<'USAGE'
Usage:
  scripts/runtime_source.sh pin <source_root_path>
  scripts/runtime_source.sh unpin
  scripts/runtime_source.sh show
  scripts/runtime_source.sh up [docker compose args...]
  scripts/runtime_source.sh down [docker compose args...]
  scripts/runtime_source.sh restart [docker compose args...]
  scripts/runtime_source.sh ps [docker compose args...]
  scripts/runtime_source.sh logs [docker compose args...]
  scripts/runtime_source.sh config [docker compose args...]
  scripts/runtime_source.sh doctor

Notes:
  - "pin" writes .runtime_source.env with absolute FPC_SOURCE_ROOT.
  - up/down/restart/ps/logs/config always use docker-compose.source-root.yml.
USAGE
}

abs_path() {
  python3 -c 'import os,sys; print(os.path.realpath(sys.argv[1]))' "$1"
}

load_runtime_env() {
  if [[ ! -f "${RUNTIME_ENV_FILE}" ]]; then
    echo "runtime source is not pinned: ${RUNTIME_ENV_FILE} is missing" >&2
    echo "run: scripts/runtime_source.sh pin <absolute_or_relative_path>" >&2
    exit 1
  fi

  # shellcheck disable=SC1090
  source "${RUNTIME_ENV_FILE}"
  if [[ -z "${FPC_SOURCE_ROOT:-}" ]]; then
    echo "FPC_SOURCE_ROOT is missing in ${RUNTIME_ENV_FILE}" >&2
    exit 1
  fi
}

compose_with_source_root() {
  load_runtime_env
  docker compose \
    -f "${BASE_COMPOSE_FILE}" \
    -f "${SOURCE_COMPOSE_FILE}" \
    --env-file "${BASE_ENV_FILE}" \
    --env-file "${RUNTIME_ENV_FILE}" \
    "$@"
}

pin_source_root() {
  if [[ $# -ne 1 ]]; then
    echo "pin expects exactly one path" >&2
    usage
    exit 1
  fi

  local requested_path="$1"
  local resolved_path
  resolved_path="$(abs_path "${requested_path}")"

  if [[ ! -d "${resolved_path}" ]]; then
    echo "source root does not exist: ${resolved_path}" >&2
    exit 1
  fi
  if [[ ! -d "${resolved_path}/frontend" ]]; then
    echo "missing frontend directory in source root: ${resolved_path}/frontend" >&2
    exit 1
  fi
  if [[ ! -d "${resolved_path}/backend" ]]; then
    echo "missing backend directory in source root: ${resolved_path}/backend" >&2
    exit 1
  fi
  if [[ ! -f "${resolved_path}/deploy/nginx/default.conf" ]]; then
    echo "missing gateway config: ${resolved_path}/deploy/nginx/default.conf" >&2
    exit 1
  fi

  cat > "${RUNTIME_ENV_FILE}" <<EOF
# generated by scripts/runtime_source.sh
FPC_SOURCE_ROOT=${resolved_path}
EOF

  echo "pinned runtime source root:"
  echo "  FPC_SOURCE_ROOT=${resolved_path}"
}

show_source_root() {
  if [[ ! -f "${RUNTIME_ENV_FILE}" ]]; then
    echo "runtime source is not pinned"
    return 1
  fi
  load_runtime_env
  echo "FPC_SOURCE_ROOT=${FPC_SOURCE_ROOT}"
}

doctor_source_root() {
  load_runtime_env

  echo "== runtime source pin =="
  echo "FPC_SOURCE_ROOT=${FPC_SOURCE_ROOT}"

  local svc cid expected

  svc="frontend"
  expected="${FPC_SOURCE_ROOT}/frontend"
  cid="$(compose_with_source_root ps -q "${svc}" | head -n1 || true)"
  if [[ -z "${cid}" ]]; then
    echo "frontend container is not running"
    return 1
  fi
  if ! docker inspect "${cid}" --format '{{range .Mounts}}{{println .Source "->" .Destination}}{{end}}' | grep -F "${expected} -> /app" >/dev/null; then
    echo "frontend mount mismatch: expected ${expected} -> /app" >&2
    return 1
  fi

  svc="api"
  cid="$(compose_with_source_root ps -q "${svc}" | head -n1 || true)"
  if [[ -z "${cid}" ]]; then
    echo "api container is not running"
    return 1
  fi
  if ! docker inspect "${cid}" --format '{{range .Mounts}}{{println .Source "->" .Destination}}{{end}}' | grep -F "${FPC_SOURCE_ROOT}/backend -> /app/backend" >/dev/null; then
    echo "api backend mount mismatch: expected ${FPC_SOURCE_ROOT}/backend -> /app/backend" >&2
    return 1
  fi
  if ! docker inspect "${cid}" --format '{{range .Mounts}}{{println .Source "->" .Destination}}{{end}}' | grep -F "${FPC_SOURCE_ROOT}/workspace -> /app/workspace" >/dev/null; then
    echo "api workspace mount mismatch: expected ${FPC_SOURCE_ROOT}/workspace -> /app/workspace" >&2
    return 1
  fi

  svc="gateway"
  cid="$(compose_with_source_root ps -q "${svc}" | head -n1 || true)"
  if [[ -z "${cid}" ]]; then
    echo "gateway container is not running"
    return 1
  fi
  if ! docker inspect "${cid}" --format '{{range .Mounts}}{{println .Source "->" .Destination}}{{end}}' | grep -F "${FPC_SOURCE_ROOT}/deploy/nginx/default.conf -> /etc/nginx/conf.d/default.conf" >/dev/null; then
    echo "gateway mount mismatch: expected ${FPC_SOURCE_ROOT}/deploy/nginx/default.conf -> /etc/nginx/conf.d/default.conf" >&2
    return 1
  fi

  echo "doctor OK: compose services are mounted from pinned source root"
}

main() {
  local command="${1:-}"
  if [[ -z "${command}" ]]; then
    usage
    exit 1
  fi
  shift || true

  case "${command}" in
    pin)
      pin_source_root "$@"
      ;;
    unpin)
      rm -f "${RUNTIME_ENV_FILE}"
      echo "removed ${RUNTIME_ENV_FILE}"
      ;;
    show)
      show_source_root
      ;;
    up|down|restart|ps|logs|config)
      compose_with_source_root "${command}" "$@"
      ;;
    doctor)
      doctor_source_root
      ;;
    *)
      usage
      exit 1
      ;;
  esac
}

main "$@"
