#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RUNTIME_ENV_FILE="${ROOT_DIR}/.runtime_source.env"
BASE_COMPOSE_FILE="${ROOT_DIR}/docker-compose.yml"
SOURCE_COMPOSE_FILE="${ROOT_DIR}/docker-compose.source-root.yml"
BASE_ENV_FILE="${ROOT_DIR}/.env"

usage() {
  cat <<'USAGE'
Usage:
  scripts/runtime_source.sh pin <source_root_path>
  scripts/runtime_source.sh pin-frontend <frontend_source_root> [<base_source_root>]
  scripts/runtime_source.sh pin-code <code_source_root> [<base_source_root>]
  scripts/runtime_source.sh unpin
  scripts/runtime_source.sh show
  scripts/runtime_source.sh up [docker compose args...]
  scripts/runtime_source.sh down [docker compose args...]
  scripts/runtime_source.sh restart [docker compose args...]
  scripts/runtime_source.sh ps [docker compose args...]
  scripts/runtime_source.sh logs [docker compose args...]
  scripts/runtime_source.sh config [docker compose args...]
  scripts/runtime_source.sh doctor

Notes:
  - "pin" writes all runtime source roots to one path.
  - "pin-frontend" pins frontend root separately; api/workspace/gateway stay on base root.
  - "pin-code" pins frontend+api from one root; workspace/gateway stay on base root.
  - up/down/restart/ps/logs/config always use docker-compose.source-root.yml.
USAGE
}

abs_path() {
  python3 -c 'import os,sys; print(os.path.realpath(sys.argv[1]))' "$1"
}

validate_source_root() {
  local root_path="$1"
  local role="$2"
  local require_frontend="${3:-0}"
  local require_backend="${4:-0}"
  local require_workspace="${5:-0}"
  local require_gateway="${6:-0}"

  if [[ ! -d "${root_path}" ]]; then
    echo "${role} source root does not exist: ${root_path}" >&2
    exit 1
  fi
  if [[ "${require_frontend}" == "1" && ! -d "${root_path}/frontend" ]]; then
    echo "${role} source root missing frontend: ${root_path}/frontend" >&2
    exit 1
  fi
  if [[ "${require_backend}" == "1" && ! -d "${root_path}/backend" ]]; then
    echo "${role} source root missing backend: ${root_path}/backend" >&2
    exit 1
  fi
  if [[ "${require_workspace}" == "1" && ! -d "${root_path}/workspace" ]]; then
    echo "${role} source root missing workspace: ${root_path}/workspace" >&2
    exit 1
  fi
  if [[ "${require_gateway}" == "1" && ! -f "${root_path}/deploy/nginx/default.conf" ]]; then
    echo "${role} source root missing gateway config: ${root_path}/deploy/nginx/default.conf" >&2
    exit 1
  fi
}

write_runtime_env() {
  local frontend_root="$1"
  local api_root="$2"
  local workspace_root="$3"
  local gateway_root="$4"
  local mode="$5"

  cat > "${RUNTIME_ENV_FILE}" <<EOF
# generated by scripts/runtime_source.sh (${mode})
FPC_SOURCE_ROOT=${api_root}
FPC_FRONTEND_SOURCE_ROOT=${frontend_root}
FPC_API_SOURCE_ROOT=${api_root}
FPC_WORKSPACE_SOURCE_ROOT=${workspace_root}
FPC_GATEWAY_SOURCE_ROOT=${gateway_root}
EOF
}

load_runtime_env() {
  if [[ ! -f "${RUNTIME_ENV_FILE}" ]]; then
    echo "runtime source is not pinned: ${RUNTIME_ENV_FILE} is missing" >&2
    echo "run: scripts/runtime_source.sh pin <absolute_or_relative_path>" >&2
    exit 1
  fi

  # shellcheck disable=SC1090
  source "${RUNTIME_ENV_FILE}"

  # Backward compatibility: old env file contained only FPC_SOURCE_ROOT.
  if [[ -z "${FPC_FRONTEND_SOURCE_ROOT:-}" && -n "${FPC_SOURCE_ROOT:-}" ]]; then
    FPC_FRONTEND_SOURCE_ROOT="${FPC_SOURCE_ROOT}"
  fi
  if [[ -z "${FPC_API_SOURCE_ROOT:-}" && -n "${FPC_SOURCE_ROOT:-}" ]]; then
    FPC_API_SOURCE_ROOT="${FPC_SOURCE_ROOT}"
  fi
  if [[ -z "${FPC_WORKSPACE_SOURCE_ROOT:-}" && -n "${FPC_SOURCE_ROOT:-}" ]]; then
    FPC_WORKSPACE_SOURCE_ROOT="${FPC_SOURCE_ROOT}"
  fi
  if [[ -z "${FPC_GATEWAY_SOURCE_ROOT:-}" && -n "${FPC_SOURCE_ROOT:-}" ]]; then
    FPC_GATEWAY_SOURCE_ROOT="${FPC_SOURCE_ROOT}"
  fi

  if [[ -z "${FPC_FRONTEND_SOURCE_ROOT:-}" || -z "${FPC_API_SOURCE_ROOT:-}" || -z "${FPC_WORKSPACE_SOURCE_ROOT:-}" || -z "${FPC_GATEWAY_SOURCE_ROOT:-}" ]]; then
    echo "runtime source vars are incomplete in ${RUNTIME_ENV_FILE}" >&2
    exit 1
  fi
}

compose_with_source_root() {
  load_runtime_env
  docker compose \
    -f "${BASE_COMPOSE_FILE}" \
    -f "${SOURCE_COMPOSE_FILE}" \
    --env-file "${BASE_ENV_FILE}" \
    --env-file "${RUNTIME_ENV_FILE}" \
    "$@"
}

pin_source_root() {
  if [[ $# -ne 1 ]]; then
    echo "pin expects exactly one path" >&2
    usage
    exit 1
  fi

  local requested_path="$1"
  local resolved_path
  resolved_path="$(abs_path "${requested_path}")"
  validate_source_root "${resolved_path}" "pin" 1 1 1 1
  write_runtime_env "${resolved_path}" "${resolved_path}" "${resolved_path}" "${resolved_path}" "all"

  echo "pinned runtime source roots (all):"
  echo "  frontend=${resolved_path}"
  echo "  api=${resolved_path}"
  echo "  workspace=${resolved_path}"
  echo "  gateway=${resolved_path}"
}

pin_frontend_source_root() {
  if [[ $# -lt 1 || $# -gt 2 ]]; then
    echo "pin-frontend expects 1 or 2 paths" >&2
    usage
    exit 1
  fi

  local frontend_requested="$1"
  local frontend_resolved
  local base_requested=""
  local base_resolved=""
  frontend_resolved="$(abs_path "${frontend_requested}")"
  validate_source_root "${frontend_resolved}" "frontend pin" 1 0 0 0

  if [[ $# -eq 2 ]]; then
    base_requested="$2"
    base_resolved="$(abs_path "${base_requested}")"
  elif [[ -f "${RUNTIME_ENV_FILE}" ]]; then
    # shellcheck disable=SC1090
    source "${RUNTIME_ENV_FILE}"
    base_resolved="$(abs_path "${FPC_API_SOURCE_ROOT:-${FPC_SOURCE_ROOT:-${ROOT_DIR}}}")"
  else
    base_resolved="${ROOT_DIR}"
  fi

  validate_source_root "${base_resolved}" "base pin" 0 1 1 1
  write_runtime_env "${frontend_resolved}" "${base_resolved}" "${base_resolved}" "${base_resolved}" "frontend-only"

  echo "pinned runtime source roots (frontend-only):"
  echo "  frontend=${frontend_resolved}"
  echo "  api=${base_resolved}"
  echo "  workspace=${base_resolved}"
  echo "  gateway=${base_resolved}"
}

pin_code_source_root() {
  if [[ $# -lt 1 || $# -gt 2 ]]; then
    echo "pin-code expects 1 or 2 paths" >&2
    usage
    exit 1
  fi

  local code_requested="$1"
  local code_resolved
  local base_requested=""
  local base_resolved=""
  code_resolved="$(abs_path "${code_requested}")"
  validate_source_root "${code_resolved}" "code pin" 1 1 0 0

  if [[ $# -eq 2 ]]; then
    base_requested="$2"
    base_resolved="$(abs_path "${base_requested}")"
  elif [[ -f "${RUNTIME_ENV_FILE}" ]]; then
    # shellcheck disable=SC1090
    source "${RUNTIME_ENV_FILE}"
    base_resolved="$(abs_path "${FPC_WORKSPACE_SOURCE_ROOT:-${FPC_API_SOURCE_ROOT:-${FPC_SOURCE_ROOT:-${ROOT_DIR}}}}")"
  else
    base_resolved="${ROOT_DIR}"
  fi

  validate_source_root "${base_resolved}" "base pin" 0 0 1 1
  write_runtime_env "${code_resolved}" "${code_resolved}" "${base_resolved}" "${base_resolved}" "code"

  echo "pinned runtime source roots (code):"
  echo "  frontend=${code_resolved}"
  echo "  api=${code_resolved}"
  echo "  workspace=${base_resolved}"
  echo "  gateway=${base_resolved}"
}

show_source_root() {
  if [[ ! -f "${RUNTIME_ENV_FILE}" ]]; then
    echo "runtime source is not pinned"
    return 1
  fi
  load_runtime_env
  echo "FPC_FRONTEND_SOURCE_ROOT=${FPC_FRONTEND_SOURCE_ROOT}"
  echo "FPC_API_SOURCE_ROOT=${FPC_API_SOURCE_ROOT}"
  echo "FPC_WORKSPACE_SOURCE_ROOT=${FPC_WORKSPACE_SOURCE_ROOT}"
  echo "FPC_GATEWAY_SOURCE_ROOT=${FPC_GATEWAY_SOURCE_ROOT}"
}

doctor_source_root() {
  load_runtime_env

  echo "== runtime source pin =="
  echo "FPC_FRONTEND_SOURCE_ROOT=${FPC_FRONTEND_SOURCE_ROOT}"
  echo "FPC_API_SOURCE_ROOT=${FPC_API_SOURCE_ROOT}"
  echo "FPC_WORKSPACE_SOURCE_ROOT=${FPC_WORKSPACE_SOURCE_ROOT}"
  echo "FPC_GATEWAY_SOURCE_ROOT=${FPC_GATEWAY_SOURCE_ROOT}"

  local svc cid expected

  svc="frontend"
  expected="${FPC_FRONTEND_SOURCE_ROOT}/frontend"
  cid="$(compose_with_source_root ps -q "${svc}" | head -n1 || true)"
  if [[ -z "${cid}" ]]; then
    echo "frontend container is not running"
    return 1
  fi
  if ! docker inspect "${cid}" --format '{{range .Mounts}}{{println .Source "->" .Destination}}{{end}}' | grep -F "${expected} -> /app" >/dev/null; then
    echo "frontend mount mismatch: expected ${expected} -> /app" >&2
    return 1
  fi

  svc="api"
  cid="$(compose_with_source_root ps -q "${svc}" | head -n1 || true)"
  if [[ -z "${cid}" ]]; then
    echo "api container is not running"
    return 1
  fi
  if ! docker inspect "${cid}" --format '{{range .Mounts}}{{println .Source "->" .Destination}}{{end}}' | grep -F "${FPC_API_SOURCE_ROOT}/backend -> /app/backend" >/dev/null; then
    echo "api backend mount mismatch: expected ${FPC_API_SOURCE_ROOT}/backend -> /app/backend" >&2
    return 1
  fi
  if ! docker inspect "${cid}" --format '{{range .Mounts}}{{println .Source "->" .Destination}}{{end}}' | grep -F "${FPC_WORKSPACE_SOURCE_ROOT}/workspace -> /app/workspace" >/dev/null; then
    echo "api workspace mount mismatch: expected ${FPC_WORKSPACE_SOURCE_ROOT}/workspace -> /app/workspace" >&2
    return 1
  fi

  svc="gateway"
  cid="$(compose_with_source_root ps -q "${svc}" | head -n1 || true)"
  if [[ -z "${cid}" ]]; then
    echo "gateway container is not running"
    return 1
  fi
  if ! docker inspect "${cid}" --format '{{range .Mounts}}{{println .Source "->" .Destination}}{{end}}' | grep -F "${FPC_GATEWAY_SOURCE_ROOT}/deploy/nginx/default.conf -> /etc/nginx/conf.d/default.conf" >/dev/null; then
    echo "gateway mount mismatch: expected ${FPC_GATEWAY_SOURCE_ROOT}/deploy/nginx/default.conf -> /etc/nginx/conf.d/default.conf" >&2
    return 1
  fi

  echo "doctor OK: compose services are mounted from pinned source root"
}

main() {
  local command="${1:-}"
  if [[ -z "${command}" ]]; then
    usage
    exit 1
  fi
  shift || true

  case "${command}" in
    pin)
      pin_source_root "$@"
      ;;
    pin-frontend)
      pin_frontend_source_root "$@"
      ;;
    pin-code)
      pin_code_source_root "$@"
      ;;
    unpin)
      rm -f "${RUNTIME_ENV_FILE}"
      echo "removed ${RUNTIME_ENV_FILE}"
      ;;
    show)
      show_source_root
      ;;
    up|down|restart|ps|logs|config)
      compose_with_source_root "${command}" "$@"
      ;;
    doctor)
      doctor_source_root
      ;;
    *)
      usage
      exit 1
      ;;
  esac
}

main "$@"
