from pathlib import Path

p = Path("backend/app/static/app.js")
s = p.read_text(encoding="utf-8", errors="replace")

marker = "STEP18C3D_MERMAID_AUTOFIT"
if marker in s:
    print("app.js already contains marker; nothing to do")
else:
    addon = "\n".join([
        "",
        "// " + marker,
        "// Auto-fit Mermaid SVG to the viewport (scale DOWN only, keep padding), so small diagrams do not become gigantic.",
        "(function(){",
        "  try {",
        "    if (window.__fpcMermaidAutofitInstalled) return;",
        "    window.__fpcMermaidAutofitInstalled = true;",
        "",
        "    function fitMermaid(opts){",
        "      opts = opts || {};",
        "      var pad = typeof opts.pad === 'number' ? opts.pad : 48;",
        "      var maxScale = typeof opts.maxScale === 'number' ? opts.maxScale : 0.85;",
        "",
        "      var wrap = document.getElementById('mermaid');",
        "      if (!wrap) return;",
        "      var svg = wrap.querySelector('svg');",
        "      if (!svg) return;",
        "",
        "      // ensure stable layout",
        "      wrap.style.overflow = 'auto';",
        "      wrap.style.padding = (pad/2) + 'px';",
        "",
        "      svg.style.display = 'block';",
        "      svg.style.margin = '0 auto';",
        "      svg.style.transformOrigin = '0 0';",
        "      svg.style.transform = 'none';",
        "",
        "      var vb = svg.viewBox && svg.viewBox.baseVal && svg.viewBox.baseVal.width ? svg.viewBox.baseVal : null;",
        "      var w = 0, h = 0;",
        "      if (vb) { w = vb.width; h = vb.height; }",
        "      if (!(w > 0 && h > 0)) {",
        "        try {",
        "          var bb = svg.getBBox();",
        "          w = bb.width; h = bb.height;",
        "          if (w > 0 && h > 0) svg.setAttribute('viewBox', bb.x + ' ' + bb.y + ' ' + bb.width + ' ' + bb.height);",
        "        } catch(e) {}",
        "      }",
        "      if (!(w > 0 && h > 0)) return;",
        "",
        "      var cw = wrap.clientWidth || 1;",
        "      var ch = wrap.clientHeight || 1;",
        "      var availW = Math.max(1, cw - pad);",
        "      var availH = Math.max(1, ch - pad);",
        "",
        "      var sW = availW / w;",
        "      var sH = availH / h;",
        "      var scale = Math.min(maxScale, sW, sH, 1);",
        "      if (!(scale > 0)) scale = 1;",
        "",
        "      svg.style.transform = 'scale(' + scale.toFixed(4) + ')';",
        "      wrap.scrollTop = 0; wrap.scrollLeft = 0;",
        "    }",
        "",
        "    window.fpcFitMermaid = fitMermaid;",
        "",
        "    function schedule(){",
        "      if (window.__fpcMermaidAutofitTimer) clearTimeout(window.__fpcMermaidAutofitTimer);",
        "      window.__fpcMermaidAutofitTimer = setTimeout(function(){",
        "        try { fitMermaid(); } catch(e) {}",
        "      }, 60);",
        "    }",
        "",
        "    function install(){",
        "      var wrap = document.getElementById('mermaid');",
        "      if (!wrap) return;",
        "      var obs = new MutationObserver(schedule);",
        "      obs.observe(wrap, { childList: true, subtree: true });",
        "      window.addEventListener('resize', schedule);",
        "      schedule();",
        "    }",
        "",
        "    if (document.readyState === 'loading') {",
        "      document.addEventListener('DOMContentLoaded', install);",
        "    } else {",
        "      install();",
        "    }",
        "  } catch(e) {}",
        "})();",
        "",
    ])
    s = s.rstrip() + "\n" + addon
    p.write_text(s, encoding='utf-8')
    print("ok: appended mermaid autofit to app.js")
