from __future__ import annotations

from .repository import _normalize_org_property_dictionary_bool as normalize_org_property_dictionary_bool, _normalize_org_property_dictionary_input_mode as normalize_org_property_dictionary_input_mode, _normalize_org_property_dictionary_key as normalize_org_property_dictionary_key, _normalize_org_property_dictionary_label as normalize_org_property_dictionary_label
